name: Trigger auto deployment for sathishjee

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/sathishjee-AutoDeployTrigger-61e4495c-3b41-4b8b-9583-c21847ab48d2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.SATHISHJEE_REGISTRY_USERNAME }}
          password: ${{ secrets.SATHISHJEE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sathishjatdot/sathishjee:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SATHISHJEE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sathishjee -g wifront-rg --server docker.io --username  ${{ secrets.SATHISHJEE_REGISTRY_USERNAME }} --password ${{ secrets.SATHISHJEE_REGISTRY_PASSWORD }}
            az containerapp update -n sathishjee -g wifront-rg --image sathishjatdot/sathishjee:${{ github.sha }}
